### ISSUE TITLE
Game doesn't run

### ISSUE THREAD

**Issue by TeddyTelanoff** [OhhhZenix/wave_rush#29]
I tried to run the app but I got greeted with a weird error message: `Disk not bootable`. Can you please fix this bug!

**Comment by OhhhZenix** [comment]
Hello @TeddyTelanoff,

1. What are your system specifications? 
2. Can you please tell me exactly did to get this?'

**Comment by TeddyTelanoff** [comment]
Here are the steps:
![IMG_20210730_092947_BURST03](https://user-images.githubusercontent.com/29633838/127684204-6d646f8b-ad3d-4e75-b288-f663fc920d6b.jpg)
![IMG_20210730_093051](https://user-images.githubusercontent.com/29633838/127684215-851e6826-84df-419f-994c-ce10edc8c47d.jpg)
![IMG_20210730_093236](https://user-images.githubusercontent.com/29633838/127684197-6a891fa2-a176-47dd-b32f-1cbc3f38fe8a.jpg)
![IMG_20210730_093111](https://user-images.githubusercontent.com/29633838/127684221-133ce07d-630d-485f-ad2c-a0e06bab07f1.jpg)

![IMG_20210730_093347](https://user-images.githubusercontent.com/29633838/127684208-cb92cce3-1ea8-4cac-872e-e6b1d10db8bf.jpg)
![IMG_20210730_093357](https://user-images.githubusercontent.com/29633838/127684213-3d5926e2-4ec8-410f-bfa7-d60ade080822.jpg)

**Comment by OhhhZenix** [comment]
This is not a related issue to the game thus no further actions will be taken.

**Comment by TeddyTelanoff** [comment]
ur no fun
